/*
* generated by Xtext
*/
package org.ptolemy.xtext.ui.contentassist;

import org.ptolemy.xtext.ui.contentassist.AbstractXActorProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class XActorProposalProvider extends AbstractXActorProposalProvider {

}
