/*
 * generated by Xtext
 */
package org.ptolemy.xtext;

import org.eclipse.xtext.conversion.impl.AbstractIDValueConverter;

import com.google.inject.Inject;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XActorRuntimeModule extends org.ptolemy.xtext.AbstractXActorRuntimeModule {

	// originally contributed by org.eclipse.xtext.generator.xbase.XbaseGeneratorFragment
	public Class<? extends org.eclipse.xtext.scoping.IScopeProvider> bindIScopeProvider() {
		return org.ptolemy.xtext.scoping.XActorScopeProvider.class;
	}

	// originally contributed by org.eclipse.xtext.generator.xbase.XbaseGeneratorFragment
	public Class<? extends org.eclipse.xtext.xbase.typing.ITypeProvider> bindITypeProvider() {
		return org.ptolemy.xtext.scoping.XActorTypeProvider.class;
	}

	public Class<? extends org.eclipse.xtext.xbase.jvmmodel.IJvmModelInferrer> bindIJvmModelInferrer() {
		return org.ptolemy.xtext.jvmmodel.XActorJvmModelInferrer.class;
	}
	
	public Class<? extends org.eclipse.xtext.xbase.scoping.featurecalls.StaticImplicitMethodsFeatureForTypeProvider.ExtensionClassNameProvider> bindExtensionClassNameProvider() {
		return org.ptolemy.xtext.scoping.ExtensionClassNameProvider.class;
	}
	
	public Class<? extends org.eclipse.xtext.xbase.scoping.featurecalls.OperatorMapping> bindOperatorMapping() {
		return org.ptolemy.xtext.scoping.OperatorMapping.class;
	}

	public Class<? extends org.eclipse.xtext.generator.IGenerator> bindIGenerator() {
		return org.ptolemy.xtext.generator.XActorGenerator.class;
	}
	
	public Class<? extends org.eclipse.xtext.xbase.compiler.XbaseCompiler> bindXBaseCompiler() {
		return org.ptolemy.xtext.generator.XActorCompiler.class;
	}

	public org.eclipse.xtext.xbase.XbaseFactory bindXbaseFactoryToInstance() {
		return org.eclipse.xtext.xbase.XbaseFactory.eINSTANCE;
	}

	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return org.ptolemy.xtext.scoping.XActorQualifiedNameProvider.class;
	}
	
	public Class<? extends org.eclipse.xtext.parsetree.reconstr.ITokenSerializer.IValueSerializer> bindIValueSerializer() {
		return org.ptolemy.xtext.formatting.XActorValueSerializer.class;
	}
}
