/*
 * generated by Xtext
 */
package org.ptolemy.xtext;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XActorRuntimeModule extends org.ptolemy.xtext.AbstractXActorRuntimeModule {

	// contributed by org.eclipse.xtext.generator.xbase.XbaseGeneratorFragment
	public Class<? extends org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy> bindIDefaultResourceDescriptionStrategy() {
		return org.ptolemy.xtext.scoping.XActorResourceDescriptionStrategy.class;
	}

	// originally contributed by org.eclipse.xtext.generator.xbase.XbaseGeneratorFragment
	public Class<? extends org.eclipse.xtext.scoping.IScopeProvider> bindIScopeProvider() {
		return org.ptolemy.xtext.scoping.XActorScopeProvider.class;
	}

	// originally contributed by org.eclipse.xtext.generator.xbase.XbaseGeneratorFragment
	public Class<? extends org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider> bindXbaseBatchScopeProvider() {
		return org.ptolemy.xtext.scoping.XActorBatchScopeProvider.class;
	}

	// contributed by org.eclipse.xtext.generator.xbase.XbaseGeneratorFragment
	public void configureSerializerIScopeProvider(com.google.inject.Binder binder) {
		binder.bind(org.eclipse.xtext.scoping.IScopeProvider.class).annotatedWith(org.eclipse.xtext.serializer.tokens.SerializerScopeProviderBinding.class).to(org.ptolemy.xtext.scoping.XActorSerializerScopeProvider.class);
	}

	// originally contributed by org.eclipse.xtext.generator.xbase.XbaseGeneratorFragment
	public Class<? extends org.eclipse.xtext.xbase.typing.ITypeProvider> bindITypeProvider() {
		return org.ptolemy.xtext.scoping.XActorTypeProvider.class;
	}

	public Class<? extends org.eclipse.xtext.xbase.jvmmodel.IJvmModelInferrer> bindIJvmModelInferrer() {
		return org.ptolemy.xtext.jvmmodel.XActorJvmModelInferrer.class;
	}
	
	public Class<? extends org.eclipse.xtext.xbase.scoping.batch.ImplicitlyImportedTypes> bindImplicitlyImportedTypes() {
		return org.ptolemy.xtext.scoping.ImplicitlyImportedTypes.class;
	}
	
	public Class<? extends org.eclipse.xtext.xbase.scoping.featurecalls.OperatorMapping> bindOperatorMapping() {
		return org.ptolemy.xtext.scoping.OperatorMapping.class;
	}

	public Class<? extends org.eclipse.xtext.generator.IGenerator> bindIGenerator() {
		return org.ptolemy.xtext.generator.XActorGenerator.class;
	}
	
	public Class<? extends org.eclipse.xtext.xbase.compiler.XbaseCompiler> bindXBaseCompiler() {
		return org.ptolemy.xtext.generator.XActorCompiler.class;
	}

	public org.eclipse.xtext.xbase.XbaseFactory bindXbaseFactoryToInstance() {
		return org.eclipse.xtext.xbase.XbaseFactory.eINSTANCE;
	}

	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return org.ptolemy.xtext.scoping.XActorQualifiedNameProvider.class;
	}
	
	public Class<? extends org.eclipse.xtext.parsetree.reconstr.ITokenSerializer.IValueSerializer> bindIValueSerializer() {
		return org.ptolemy.xtext.formatting.XActorValueSerializer.class;
	}

}
