/*
* generated by Xtext
*/
package org.ptolemy.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class XActorOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
