/*
 * generated by Xtext
 */
package org.ptolemy.graphiti;

import org.osgi.framework.Bundle;
import org.ptolemy.graphiti.generic.editor.ActorDiagramEditorExecutableExtensionFactory;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PtolemyActorDiagramEditorExecutableExtensionFactory extends ActorDiagramEditorExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Activator.getDefault().getBundle();
	}

	@Override
	protected Injector getInjector() {
		return Activator.getDefault().getInjector();
	}
}