<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="caltrop"
    nsURI="org.ptolemy.ecore.caltrop" nsPrefix="caltrop">
  <eClassifiers xsi:type="ecore:EClass" name="CaltropActorImpl">
    <eTypeParameters name="P">
      <eBounds eClassifier="ecore:EClass actor.ecore#//AbstractIOPort"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
        eType="#//StateVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//FireAction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initActions" upperBound="-1"
        eType="#//OutputAction" containment="true"/>
    <eGenericSuperTypes eClassifier="ecore:EClass actor.ecore#//AtomicActorImpl">
      <eTypeArguments eTypeParameter="#//CaltropActorImpl/P"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActorParameter" eSuperTypes="actor.ecore#//Parameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypedInputPort" eSuperTypes="actor.ecore#//AbstractTypedIOPort"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypedOutputPort" eSuperTypes="actor.ecore#//AbstractTypedIOPort"/>
  <eClassifiers xsi:type="ecore:EClass" name="StateVariable" eSuperTypes="actor.ecore#//Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FireAction" eSuperTypes="#//OutputAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputPatterns" upperBound="-1"
        eType="#//InputPattern" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputAction" eSuperTypes="kernel.ecore#//NamedObj">
    <eOperations name="getInputPatterns" upperBound="-1" eType="#//InputPattern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guardExpression" eType="ecore:EClass http://www.eclipse.org/xtext/xbase/Xbase#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputPatterns" upperBound="-1"
        eType="#//OutputPattern" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodyExpression" eType="ecore:EClass http://www.eclipse.org/xtext/xbase/Xbase#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortPattern" abstract="true">
    <eOperations name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repeatExpression" eType="ecore:EClass http://www.eclipse.org/xtext/xbase/Xbase#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="channels" eType="#//ChannelSelector"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portRef" eType="ecore:EClass kernel.ecore#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPattern" eSuperTypes="#//PortPattern">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variables" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPattern" eSuperTypes="#//PortPattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueExpressions" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/xtext/xbase/Xbase#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChannelSelector" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionChannelSelector" eSuperTypes="#//ChannelSelector">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="many" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyExpressions" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/xtext/xbase/Xbase#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeywordChannelSelector" eSuperTypes="#//ChannelSelector">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyword" eType="#//ChannelSelectorKeyword"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ChannelSelectorKeyword">
    <eLiterals name="ALL" value="-1"/>
    <eLiterals name="ANY" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OldActionVariableValueRef" eSuperTypes="http://www.eclipse.org/xtext/xbase/Xbase#//XAbstractFeatureCall"/>
</ecore:EPackage>
