<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="xactor"
    nsURI="org.ptolemy.ecore.xactor" nsPrefix="xactor">
  <eClassifiers xsi:type="ecore:EClass" name="EntityFolder">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityContainers" upperBound="-1"
        eType="#//EntityFolder" containment="true"/>
    <eGenericSuperTypes eClassifier="ecore:EClass kernel.ecore#//EntityContainer">
      <eTypeArguments eClassifier="ecore:EClass kernel.ecore#//Port"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActorModel" eSuperTypes="#//EntityFolder">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//ImportDirective" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportDirective">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
